dishes/urls.py
from django.conf.urls import patterns, url
from dishes import views
from dishes.views import DishesList, DishAbout

urlpatterns = patterns(
    '',

    url(r'(?P<establishment_id>\d+)/$', DishesList.as_view(), name='dishes_without_category'),

    url(r'(?P<establishment_id>\d+)/(?P<dish_category>\d+)?', DishesList.as_view(), name='dishes_with_category'),

    url(r'dish/(?P<dish_id>\d+)/?', DishAbout.as_view(), name='dish_about'),

    # url for ajax requests
    url(r'update_cart/$', views.add_dish, name='cart_updating'),

    # url for ajax requests
    url(r'load_cart/$', views.load_cart, name='cart_loading'),
)

establishments/urls.py
from django.conf.urls import patterns, url
from establishments import views
from establishments.views import EstablishmentsList

urlpatterns = patterns(
    '',

    url(r'^$', EstablishmentsList.as_view(), name='home'),

    url(r'(?P<city_id>\d+)/$', EstablishmentsList.as_view(), name='establishments'),

    # url for ajax requests
    url(r'flush_session/$', views.delete_expired_session_data, name='session_cleaning'),

    url(r'^about/$', views.about_page_view, name='about_page'),
)

wanna_eat/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = patterns(
    '',

    # редирект с корня сайта на страницу выбора заведения для города
    url(r'^$', RedirectView.as_view(url=r'city/'), name="home_page"),

    # редирект на файл urls в приложении establishments
    url(r'^city/', include('establishments.urls')),

    # редирект на файл urls в приложении establishments
    url(r'^establishment/', include('dishes.urls')),

    # редирект на файл urls в приложении orders
    url(r'^order/', include('orders.urls')),

    # страница пользователя организации
    url(r'^employee/', include('employees.urls')),

    # админка сайта
    url(r'^admin/', include(admin.site.urls)),
)

establishments/models.py
from django.db import models


class City(models.Model):
    name = models.CharField(
        max_length=30,
        unique=True,
        verbose_name='Название'
    )

    def __str__(self):
        return self.name


class Establishment(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,
        verbose_name='Название'
    )
    city = models.ForeignKey(
        City,
        related_name='establishments',
        verbose_name='Город'
    )
    establishment_image = models.ImageField(
        upload_to='establishments/',
        blank=True,
        null=True,
        verbose_name='Логотип',
    )
    description = models.CharField(
        max_length=300,
        blank=True,
        null=True,
        verbose_name='Описание'
    )
    email = models.CharField(
        max_length=30,
        unique=True,
        verbose_name='Электронная почта'
    )

    def __str__(self):
        return self.name


class EstablishmentBranch(models.Model):
    establishment = models.ForeignKey(
        Establishment,
        related_name='branches',
        verbose_name='Заведение'
    )
    address = models.CharField(
        max_length=80,
        verbose_name='Адресс'
    )
    order_phone_number = models.CharField(
        max_length=10,
        verbose_name='Телефон заказов'
    )
    help_phone_number = models.CharField(
        max_length=10,
        verbose_name='Телефон для справок'
    )

    def __str__(self):
        return '{0}, {1}'.format(
            self.establishment,
            self.address,
        )


class BranchHall(models.Model):
    HALL_TYPE_SMOKING = '0'
    HALL_TYPE_NONSMOKING = '1'

    HALL_TYPE = (
        (HALL_TYPE_SMOKING, 'Курящий'),
        (HALL_TYPE_NONSMOKING, 'Не курящий'),
    )

    branch = models.ForeignKey(
        EstablishmentBranch, related_name='halls',
        verbose_name='Филиал заведения'
    )
    type = models.CharField(
        max_length=1,
        choices=HALL_TYPE,
        verbose_name='Тип зала'
    )

    @property
    def free_tables_count(self):
        return self.dinner_wagons.filter(
            is_served=1
        ).len()

    def __str__(self):
        return '{0} - {1}'.format(
            self.branch,
            self.get_type_display(),
        )


class DinnerWagon(models.Model):
    hall = models.ForeignKey(
        BranchHall,
        related_name='dinner_wagons',
        blank=True,
        null=True,
        verbose_name='Зал заведения'
    )
    seats = models.IntegerField(
        default=2,
        verbose_name='Количество мест'
    )

    def __str__(self):
        return '{0}: {1}'.format(
            self.hall,
            self.seats,
        )

establishments/views.py
from django.http import HttpResponse
from django.views.generic import ListView
from establishments.models import City, Establishment
from django.shortcuts import render


class EstablishmentsList(ListView):
    model = City
    template_name = 'establishments/establishments.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        city_id = self.kwargs.get('city_id')
        if city_id is not None:
            default_city = City.objects.filter(id=city_id)[0] or City.objects.first()
        else:
            default_city = City.objects.first()
        context['default_city'] = default_city
        context['establishment_list'] = Establishment.objects.filter(city=default_city)
        return context


def delete_expired_session_data(request):
    """Очищает истекшие ключи сессии"""
    if request.is_ajax():
        # TODO очищать только, когда пользователь заходит первый раз в сессию на эту страницу
        request.session.flush()
        message = 'ok'
    else:
        message = 'error'
    return HttpResponse(message)


def about_page_view(request):
    return render(
        request,
        'establishments/about.html',
        {

        }
    )

establishments/templates/establishments/about.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

        <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <h1>О сайте:</h1>
            <p>данный сайт разработан в рамках курсового проекта по дисциплине "Технологии разработки программного обеспечения" </p>
          </div>
          <div class="container">
            <div class="col-xs-9">
                выаваааааааааааааааааааааааааааааааааааааааа ааааааааа ааааааааааааа ааааааа ааааааааааа аааааааааа ааааааа ааааааа
                ываааааааааааааааааааааааааааааааааа
                ываааааааааааааааааааааааааааааааааааа аппрпрапр аапр апра  арапра  пра
            </div>
          </div>


        </div><!--/.col-xs-12.col-sm-9-->

      </div><!--/row-->

{% endblock %}

establishments/templates/establishments/establishments.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <h1>Добро пожаловать!</h1>
            <p>Вас приветствует сервис для совершения заказов в любом ресторане вашего города. Чтобы начать выберите интересующее вас заведение.</p>
          </div>
          <div class="row">
              {% for establishment in establishment_list %}
            <div class="col-xs-6 col-lg-4">
              <h3>{{ establishment.name }}</h3>
                <img src="{% static 'images/'|add:establishment.establishment_image.name %}" class="img-thumbnail">
              <p>{{ establishment.description }}</p>
                <p><a class="btn btn-default" href="{% url 'dishes_without_category' establishment_id=establishment.id %}" role="button">Меню</a></p>
            </div><!--/.col-xs-6.col-lg-4-->
              {% endfor %}
          </div><!--/row-->
        </div><!--/.col-xs-12.col-sm-9-->

        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="list-group">
              {% for city in city_list %}
                {% if city == default_city %}
                    <a href="/city/{{ city.id }}" class="list-group-item active">{{ city }}</a>
                {% else %}
                    <a href="/city/{{ city.id }}" class="list-group-item">{{ city }}</a>
                {% endif %}
              {% endfor %}
          </div>
        </div><!--/.sidebar-offcanvas-->
      </div><!--/row-->
{% endblock %}

{% block scripts %}

    <script type="text/javascript">
        $(document).ready(function() {
            $.get("{% url 'session_cleaning' %}");
        })
    </script>

{% endblock %}