dishes/urls.py
from django.conf.urls import patterns, url
from dishes import views
from dishes.views import DishesList, DishAbout

urlpatterns = patterns(
    '',

    url(r'(?P<establishment_id>\d+)/$', DishesList.as_view(), name='dishes_without_category'),

    url(r'(?P<establishment_id>\d+)/(?P<dish_category>\d+)?', DishesList.as_view(), name='dishes_with_category'),

    url(r'dish/(?P<dish_id>\d+)/?', DishAbout.as_view(), name='dish_about'),

    # url for ajax requests
    url(r'update_cart/$', views.add_dish, name='cart_updating'),

    # url for ajax requests
    url(r'load_cart/$', views.load_cart, name='cart_loading'),
)

orders/urls.py
from django.conf.urls import patterns, url
from orders import views

urlpatterns = patterns(
    '',

    url(r'cart/(?P<cart_state>\d+)/$', views.view_cart, name='cart'),

    url(r'cart/orders/$', views.view_orders, name='cart_orders'),

    # url for ajax
    url(r'cart/orders/dish_list/$', views.view_establishment_dish_list, name='cart_orders_establishment_dish_list'),

    # url for ajax
    url(r'cart/increment_dish/$', views.increment_dish, name='cart_dish_incrementation'),

    # url for ajax
    url(r'cart/decrement_dish/$', views.decrement_dish, name='cart_dish_decrementation'),

    url(r'make_order/(?P<establishment_id>\d+)/(?P<order_type>\d+)/$', views.get_order_form, name='get_form'),

    url(r'my_orders/$', views.get_user_form, name='get_user_form'),

    # url for ajax
    url(r'my_orders/dish_list/$', views.view_order_dish_list, name='view_order_dish_list')
)

wanna_eat/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = patterns(
    '',

    # редирект с корня сайта на страницу выбора заведения для города
    url(r'^$', RedirectView.as_view(url=r'city/'), name="home_page"),

    # редирект на файл urls в приложении establishments
    url(r'^city/', include('establishments.urls')),

    # редирект на файл urls в приложении establishments
    url(r'^establishment/', include('dishes.urls')),

    # редирект на файл urls в приложении orders
    url(r'^order/', include('orders.urls')),

    # страница пользователя организации
    url(r'^employee/', include('employees.urls')),

    # админка сайта
    url(r'^admin/', include(admin.site.urls)),
)

orders/models.py
from datetime import timedelta
from django.db import models
from dishes.models import EstablishmentDish
from employees.models import Employee
from establishments.models import EstablishmentBranch, DinnerWagon


class Order(models.Model):
    STATE_NONE = '0'
    STATE_UNDER_CONSIDERATION = '1'
    STATE_IN_PROGRESS = '2'
    STATE_CANCELED = '3'
    STATE_DONE = '4'

    ORDER_STATE = (
        (STATE_NONE, 'Не установлен'),
        (STATE_UNDER_CONSIDERATION, 'На рассмотрении'),
        (STATE_IN_PROGRESS, 'Выполняется'),
        (STATE_CANCELED, 'Отменен'),
        (STATE_DONE, 'Выполнен'),
    )

    TYPE_DINNER_WAGON = '0'
    TYPE_PICKUP = '1'
    TYPE_DELIVERY = '2'

    ORDER_TYPE = (
        (TYPE_DINNER_WAGON, 'Бронирование столика'),
        (TYPE_PICKUP, 'Заказ самовывоза'),
        (TYPE_DELIVERY, 'Заказ доставки'),
    )

    client_phone = models.CharField(
        max_length=10,
        verbose_name='Телефон клиента'
    )
    type = models.CharField(
        max_length=1,
        choices=ORDER_TYPE,
        verbose_name='Тип заказа'
    )

    state = models.CharField(
        max_length=1,
        choices=ORDER_STATE,
        default=STATE_NONE,
        verbose_name='Состояние заказа'
    )
    order_date = models.DateField(
        auto_now_add=True,
        verbose_name='Дата заказа'
    )

    execute_date = models.DateField(verbose_name='Дата исполнения')

    execute_time = models.TimeField(verbose_name='Время исполнения')

    @property
    def expire_date(self):
        if self.state == self.STATE_DONE:
            return self.execute_date + timedelta(days=30)

    contact_account = models.ForeignKey(
        Employee,
        related_name='orders',
        verbose_name='Контактное лицо организации'
    )
    # особенные поля, необходимые для определенных видов заказов

    # для заказа самовывоза и бронирования столика
    establishment_branch = models.ForeignKey(
        EstablishmentBranch,
        blank=True,
        null=True,
        related_name='+',
        verbose_name='Филиал заведения'
    )
    # для заказа столика
    dinner_wagon = models.ForeignKey(
        DinnerWagon,
        blank=True,
        null=True,
        related_name='orders',
        verbose_name='Столик'
    )
    # для доставки
    delivery_address = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        verbose_name='Адрес доставки'
    )

    # arguments: type='table' or type='pickup 'or type='delivery'
    def make(self, **kwargs):
        if kwargs.get('type') is not None:
            if kwargs.get('type') == 'table':
                self.type = self.TYPE_DINNER_WAGON
                self.state = self.STATE_UNDER_CONSIDERATION
            elif kwargs.get('type') == 'pickup':
                self.type = self.TYPE_PICKUP
                self.state = self.STATE_UNDER_CONSIDERATION
            elif kwargs.get('type') == 'delivery':
                self.type = self.TYPE_DELIVERY
                self.state = self.STATE_UNDER_CONSIDERATION

    def accept(self):
        self.state = self.STATE_IN_PROGRESS

    def decline(self):
        self.state = self.STATE_CANCELED

    def perform(self):
        self.state = self.STATE_DONE

    def __str__(self):
        return \
            self.client_phone.__str__() + \
            " " + self.execute_date.__str__() + \
            " " + self.execute_time.__str__() + \
            " " + self.get_type_display() + \
            " " + self.contact_account.__str__()

    def delete(self, using=None):
        super().delete(using)
        OrdersCartRow.objects.filter(order=self).delete()


class OrdersCartRow(models.Model):
    establishment_dish = models.ForeignKey(
        EstablishmentDish,
        verbose_name='Блюдо заведения'
    )
    dishes_count = models.IntegerField(
        default=1,
        verbose_name='Количество блюд'
    )
    order = models.ForeignKey(
        Order,
        related_name='rows',
        verbose_name='Строка заказа'
    )

orders/forms.py
from datetime import datetime, timedelta
from django import forms
from django.core.exceptions import ValidationError
from establishments.models import EstablishmentBranch, BranchHall, DinnerWagon
from orders.models import Order


class TableForm(forms.Form):
    address = forms.ChoiceField(
        label='Адрес заведения',
        error_messages={
            'required': 'Поле адреса заведения не может быть пустым'
        },
        required=True
    )
    hall = forms.ChoiceField(
        label='Тип зала заведения',
        error_messages={
            'required': 'Поле типа зала заведения не может быть пустым'
        },
        required=True
    )
    date = forms.DateField(
        label='Дата бронирования',
        input_formats=['%Y-%m-%d'],
        widget=forms.DateInput(
            attrs={
                'type': 'date',
                'placeholder': 'ДД-ММ-ГГГГ'
            },
        ),
        error_messages={
            'required': 'Поле даты бронирования не может быть пустым',
            'invalid': 'Неверный формат записи даты бронирования'
        },
        required=True
    )
    time = forms.TimeField(
        label='Время бронирования',
        input_formats=['%H:%M'],
        widget=forms.TimeInput(
            attrs={
                'type': 'time',
                'placeholder': 'ЧЧ:ММ'
            },
        ),
        error_messages={
            'required': 'Поле времени бронирования не может быть пустым',
            'invalid': 'Неверный формат записи времени бронирования'
        },
        required=True
    )
    table = forms.ChoiceField(
        label='Количество мест за столиком',
        error_messages={
            'required': 'Поле столика заведения не может быть пустым'
        },
        help_text='Если поле пустое, то свободных столиков нет',
        required=True
    )
    phone = forms.CharField(
        label='Ваш контактный телефон',
        widget=forms.TextInput(attrs={'placeholder': '9004001020'}),
        max_length=10,
        error_messages={
            'required': 'Поле номера телефона не может быть пустым'
        },
        help_text='Необходим для обработки и подтверждения заказа сотрудниками заведения.',
        required=True
    )

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        symbols_list = list(phone)
        if symbols_list.__len__() < 10:
            raise forms.ValidationError('Номер телефона должен состоять из 10 цифр')
        for symbol in symbols_list:
            try:
                int_value = int(symbol)
                if int_value < 0:
                    raise forms.ValidationError('Неверный номер телефона')
            except ValueError:
                raise forms.ValidationError('Неверный номер телефона')
        return phone

    def clean(self):
        order_date = self.cleaned_data.get('date')
        order_time = self.cleaned_data.get('time')
        if order_date is None:
            raise ValidationError('Поле даты бронирования не должо быть пустым')
        elif order_time is None:
            raise ValidationError('Поле времени бронирования не должо быть пустым')
        # TODO учитывать временные зоны (date_time содержит дату с учетом временой зоны) сейчас - абсолютоное время
        execution_date_time = datetime(
            order_date.year,
            order_date.month,
            order_date.day,
            order_time.hour,
            order_time.minute
        )
        date_time_border = datetime.now() + timedelta(hours=2)
        if execution_date_time <= date_time_border:
            error_message = 'Невозможно оформить заказ на выбранное время'
            self.add_error('date', error_message)
            self.add_error('time', error_message)

    def __init__(self, establishment_id, branch_id, hall_type, order_date, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if establishment_id != -1:
            if EstablishmentBranch.objects.filter(establishment__id=establishment_id).exists():
                self.fields['address'] = forms.ChoiceField(
                    choices=[(branch.id, branch.address) for branch in EstablishmentBranch.objects.filter(
                        establishment__id=establishment_id
                    )],
                    label='Адрес заведения',
                    required=True
                )

                if branch_id == -1 and hall_type == -1 and order_date == -1:
                    # загружаем данные формы по умолчанию
                    default_branch = EstablishmentBranch.objects.filter(establishment__id=establishment_id).first()
                    self.fields['hall'] = forms.ChoiceField(
                        choices=[(hall.type, hall.get_type_display()) for hall in BranchHall.objects.filter(
                            branch=default_branch
                        )],
                        label='Тип зала заведения',
                        error_messages={
                            'required': 'Поле адреса заведения не может быть пустым'
                        },
                        required=True
                    )

                    default_date = datetime.now() + timedelta(days=1)

                    default_hall = BranchHall.objects.filter(branch=default_branch).first()
                    # определяем, какие столики на заданную дату свободны
                    tables_in_hall = DinnerWagon.objects.filter(hall=default_hall)
                    hall_tables_specification = {}
                    for table in tables_in_hall:
                        if hall_tables_specification.get(table.seats) is None:
                            hall_tables_specification[table.seats] = 1
                        else:
                            hall_tables_specification[table.seats] += 1
                    table_orders_for_default_date = Order.objects.filter(
                        execute_date=default_date.date(),
                        type=Order.TYPE_DINNER_WAGON,
                        establishment_branch=default_branch,
                        dinner_wagon__hall=default_hall
                    )
                    order_tables_specification = {}
                    for order in table_orders_for_default_date:
                        if order_tables_specification.get(order.dinner_wagon.seats) is None:
                            order_tables_specification[order.dinner_wagon.seats] = 1
                        else:
                            order_tables_specification[order.dinner_wagon.seats] += 1
                    keys_for_delete = []
                    for hall_table_key in hall_tables_specification.keys():
                        if order_tables_specification.get(hall_table_key) is not None:
                            hall_tables_specification[hall_table_key] -= 1
                            if hall_tables_specification[hall_table_key] == 0:
                                keys_for_delete.append(hall_table_key)
                    for key in keys_for_delete:
                        del hall_tables_specification[key]
                    # в результате hall_tables_specification пуст или содержит свободные столики на заданную дату
                    self.fields['table'] = forms.ChoiceField(
                        choices=[(key, key) for key in hall_tables_specification.keys()],
                        error_messages={
                            'required': 'Поле столика заведения не может быть пустым'
                        },
                        help_text='Если поле пустое, то свободных столиков нет',
                        label='Количество мест за столиком',
                        required=True
                    )
                elif branch_id != -1 and hall_type == -1 and order_date == -1:
                    # загрузка формы после изменения выбора филиала заведения
                    default_branch = EstablishmentBranch.objects.filter(
                        establishment__id=establishment_id,
                        id=branch_id
                    ).first()
                    self.fields['hall'] = forms.ChoiceField(
                        choices=[(hall.type, hall.get_type_display()) for hall in BranchHall.objects.filter(
                            branch=default_branch
                        )],
                        label='Тип зала заведения',
                        required=True
                    )

                    default_date = datetime.now() + timedelta(days=1)

                    default_hall = BranchHall.objects.filter(branch=default_branch).first()
                    # определяем, какие столики на заданную дату свободны
                    tables_in_hall = DinnerWagon.objects.filter(hall=default_hall)
                    hall_tables_specification = {}
                    for table in tables_in_hall:
                        if hall_tables_specification.get(table.seats) is None:
                            hall_tables_specification[table.seats] = 1
                        else:
                            hall_tables_specification[table.seats] += 1
                    table_orders_for_default_date = Order.objects.filter(
                        execute_date=default_date.date(),
                        type=Order.TYPE_DINNER_WAGON,
                        establishment_branch=default_branch,
                        dinner_wagon__hall=default_hall
                    )
                    order_tables_specification = {}
                    for order in table_orders_for_default_date:
                        if order_tables_specification.get(order.dinner_wagon.seats) is None:
                            order_tables_specification[order.dinner_wagon.seats] = 1
                        else:
                            order_tables_specification[order.dinner_wagon.seats] += 1
                    keys_for_delete = []
                    for hall_table_key in hall_tables_specification.keys():

orders/templates/orders/make_order_form.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
        <div class="page-header">
            <h1>Заказы: </h1>
        </div>
        <div class="row">
            {% if show_form == 1 %}
            <div class="col-xs-9">
                <div class="panel panel-default"  style="border-color:#eeeeee">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-10">
                                <h3 class="panel-title" >Детали заказа</h3>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-xs-10">
                                <form name="make_order_form" id="order_form" action="{% url 'get_form' establishment_id=establishment_id order_type=current_order_type %}" method="post">
                                    {% csrf_token %}
                                    {% for field in form %}
                                    {% if field.label == 'Время бронирования' and current_order_type == '0' %}
                                    <input type="submit" value="Показать столики" onclick="showTables()" />
                                    <div><p></p></div> <!-- Исключительно для пропуска строки в текущем шаблоне верстки -->
                                    <div id="hidden_area">
                                    {% endif %}
                                    <div>
                                        {{ field.label }}
                                    </div>
                                    <div>
                                        {{ field }}
                                        {% if field.field.required %}
                                            <span>*</span>
                                        {% endif %}
                                        {% if show_custom_date_error == 1 and field.label == 'Дата бронирования' %}
                                        Неверная дата
                                        {% endif %}
                                        {% if show_errors == 1 %}
                                        {% for error in field.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    {% endif %}
                                    </div>
                                    <div>
                                        {{ field.help_text }}
                                    </div>
                                    <div><p></p></div> <!-- Исключительно для пропуска строки в текущем шаблоне верстки -->
                                    {% endfor %}
                                    {% if current_order_type == '0' %}
                                    </div>
                                    {% endif %}
                                    <input id="id_address_changed" type="hidden" name="address_changed" value="0" />
                                    <input id="id_show_tables" type="hidden" name="show_tables" value="0" />
                                    <input id="id_order_type" type="hidden" name="order_type" value="{{ current_order_type }}" />
                                    <input type="submit" value="Оформить заказ" onclick="sendOrder()"/>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-3 sidebar-offcanvas" id="sidebar" role="navigation">
                <div class="list-group">
                    {% for type, name in order_types_list %}
                        <a href="{% url 'get_form' establishment_id=establishment_id order_type=type %}" class="list-group-item {% if type == current_order_type %} active {% endif %}">
                            {{ name }}
                        </a>
                    {% endfor %}
                </div>
            </div><!--/.sidebar-offcanvas-->
            {% endif %}
        </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $(document).keydown(function(eventObject) {
            if (eventObject.which == 13) { // нажата клавиша Enter
                document.forms["make_order_form"].submit();
            }
        })

        function sendOrder() {
            $("#id_show_tables").val("0");
        }

        function showTables() {
            $("#id_show_tables").val("1");
        }

        // если в элементах управления что-то изменяется, то область div id="hidden_area" скрывается
        // скрывается, только, если это происходит на форме бронирования столика
        $("#id_hall, #id_date").change(function() {
            if ($("#id_order_type").val() == "0") {
                $("#hidden_area").html("");
            }
        })

        // отправка данных на форму только, если это форма бронирования столика
        $("#id_address").change(function() {
            if ($("#id_order_type").val() == "0") {
                $("#id_address_changed").val("1");
                document.forms["make_order_form"].submit();
            }
        })
    </script>
{% endblock %}

orders/templates/orders/order_created.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

    <div class="page-header">
        <h1>Заведение "{{ establishment_name }}"</h1>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Ваш заказ успешно оформлен.
                    </h3>
                </div>
                <div class="panel-body">
                    <p>Заказ поступил на рассмотрение администрацией заведения. Они могут связаться с Вами по указанному в заказе телефону.</p>
                    <p>Вы можете посмотреть свои заказы в меню "Мои заказы" нашего сайта.</p>
                    <p>Вы также можете сами связаться с администрацией заведения:</p>
                    <p>Електронная почта: {{ establishment_email }}</p>
                    {% if order_type != '2' %}
                        <p>Телефон заказов: {{ establishment_branch_order_phone }}</p>
                        <p>Телефон для справок: {{ establishment_branch_help_phone }}</p>
                    {% endif %}
                    <a class="btn btn-default" href="{% url 'dishes_without_category' establishment_id=establishment_id %}">Вернуться в меню</a>
                    <a class="btn btn-default" href="{% url 'cart' cart_state=1 %}">Сделать еще заказ</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
{% endblock %}

orders/templates/orders/orders.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
         <div class="col-xs-6 col-lg-8">
             {% if show_form == 1 %}
                <form name="make_order_form" id="order_form" action="{% url 'get_form' establishment_id=establishment_id order_type=current_order_type %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div>
                            {{ field.label }}
                        </div>
                        <div>
                            {{ field }}
                            {% if field.field.required %}
                                <span>*</span>
                            {% endif %}
                            {% if show_errors == 1 %}
                                {% for error in field.errors %}
                                    {{ error }}
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div>
                            {{ field.help_text }}
                        </div>
                        <div><p></p></div> <!-- Исключительно для пропуска строки в текущем шаблоне верстки -->
                    {% endfor %}
                    <input id="id_address_changed" type="hidden" name="address_changed" value="0" />
                    <input id="id_hall_changed" type="hidden" name="hall_changed" value="0" />
                    <input type="submit" value="Оформить заказ" />
                </form>
         </div>
         <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
            <div class="list-group">
                {% for type, name in order_types_list %}
                    <a href="{% url 'get_form' establishment_id=establishment_id order_type=type %}" class="list-group-item {% if type == current_order_type %} active {% endif %}">
                        {{ name }}
                    </a>
                {% endfor %}
            </div>
         </div><!--/.sidebar-offcanvas-->
        {% endif %}
      </div><!--/row-->
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $(document).keydown(function(eventObject) {
            if (eventObject.which == 13) { // нажата клавиша Enter
                document.forms["make_order_form"].submit();
            }
        })

        $("#id_address").change(function() {
            $("#id_address_changed").val("1");
            document.forms["make_order_form"].submit();
        })

        $("#id_hall").change(function() {
            $("#id_hall_changed").val("1");
            document.forms["make_order_form"].submit();
        })
    </script>
{% endblock %}

orders/templates/orders/user_orders.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

    <div class="page-header">
        <h1>Ваши заказы</h1>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Получить заказы по номеру телефона
                    </h3>
                </div>
                <div class="panel-body">
                    <form name="user_orders_form" action="{% url 'get_user_form' %}" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div>
                                {{ field.label }}
                            </div>
                            <div>
                                {{ field }}
                                {% if field.field.required %}
                                    <span>*</span>
                                {% endif %}
                                {% if show_errors == 1 %}
                                    {% for error in field.errors %}
                                        {{ error }}
                                    {% endfor %}
                                {% endif %}
                            </div>
                            <div>
                                {{ field.help_text }}
                            </div>
                            <div><p></p></div> <!-- Исключительно для пропуска строки в текущем шаблоне верстки -->
                        {% endfor %}
                        <input type="submit" value="Показать" />
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% if is_valid == 1 %}
        {% for order in orders %}
        <div class="row">
            <div class="col-xs-10">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            {{ order.get_type_display }}
                        </h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-xs-3">
                                Статус: <strong>{{ order.get_state_display }}</strong>
                            </div>
                            <div class="col-xs-4">
                                <p>{{ order.establishment_branch.establishment.name }} - {{ order.establishment_branch.establishment.email }}</p>
                                {% if order.type != '2' %}
                                    {{ order.establishment_branch.address }} - {{ order.establishment_branch.help_phone_number }}
                                {% endif %}
                            </div>
                            <div class="col-xs-2">
                                <a class="btn btn-link" onclick="viewOrderDishList({{ order.id }})">Заказ</a>
                            </div>
                            <div class="col-xs-3">
                                {{ order.execute_date }} {{ order.execute_time }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-10">
                <div class="alert alert-info" id="popup{{ order.id }}">
                    <span id="order_rows{{ order.id }}"></span>
                    <div class="row">
                        <div class="col-xs-2 ">
                            <button type="button" class="btn btn-primary" onclick="hidePopUp()" style="width:100%;">Закрыть</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    {% endif %}

{% endblock %}

{% block scripts %}

    <script type="text/javascript">
        $(document).keydown(function(eventObject) {
            if (eventObject.which == 13) { // нажата клавиша Enter
                document.forms["user_orders_form"].submit();
            } else if (eventObject.which == 27) { // нажата клавиша Esc
                hidePopUp();
            }
        })

        function viewOrderDishList(order_id) {
            $.get("{% url 'view_order_dish_list' %}", {"id": order_id}, function(data) {
                if (data != "error") {
                    var order_specification = jQuery.parseJSON(data);
                    var order_price = order_specification.order_price;
                    var dish_list = order_specification.order_components;
                    var order_rows = [];
                    for (var i = 0; i < dish_list.length; i++) {
                        order_rows[i] = dish_list[i].dish_name + ": " + dish_list[i].dish_count + "x " + dish_list[i].dish_price + " р.";
                    }
                    showPopUp(order_id, order_price, order_rows);
                } else {

                }
            })
        }

        $(document).ready(function() {
            hidePopUp();
        })

        function showPopUp(order_id, order_price, order_rows) {
            hidePopUp();
            var row_id = "#order_rows" + order_id;
            $(row_id).html("");
            var out_str = "<p>Цена заказа: " + "<strong>" + order_price + " р.</strong></p>";
            for (var i = 0; i < order_rows.length; i++) {
                out_str += "<p>" + order_rows[i] + "</p>";
            }
            $(row_id).html(out_str);
            var popup_id = "#popup" + order_id;
            $(popup_id).show();
        }

        function hidePopUp() {
            $(".alert").hide();
        }
    </script>

{% endblock %}